# Generated by Django 4.1.7 on 2023-04-23 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
    ]
