# Generated by Django 4.1.7 on 2023-04-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_child_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='child',
            name='status',
            field=models.CharField(choices=[('At School', 'At School'), ('In Transit', 'In Transit'), ('Dismissed', 'Dismissed')], default='At School', max_length=20),
        ),
    ]
